### ISSUE TITLE
E117: Unknown function: smartinput_endwise#define_default_rules

### ISSUE THREAD

**Issue by takano32** [cohama/vim-smartinput-endwise#1]
Now, this plugin doesn't work well, may be.

Add my vimrc below lines.

```
NeoBundle 'kana/vim-smartinput'
NeoBundle 'cohama/vim-smartinput-endwise'
call smartinput_endwise#define_default_rules()
```

And smartinput works well.

Thanks.

**Comment by cohama** [comment]
There is no problem for me.
Is 'runtimepath' properly added?
Please confirm the output of `:set runtimepath`.
Probably you need `:NeoBundleReinstall` or `:NeoBundleClearCache`.

**Comment by takano32** [comment]
Sorry.

This may be caused by conflict of some plugins.
I'll try remove all NeoBundle lines except lines for smartinput-endwise.

Thanks.
