### ISSUE TITLE
iskeywordにコンマが含まれていなくてもrubyのブロック引数を複数指定したい

### ISSUE THREAD

**Issue by uplus** [cohama/vim-smartinput-endwise#2]
rubyのdo ~ endブロックの正規表現を見ると\kを使用していますが、私の環境ではiskeywordにコンマを含めていないためブロック引数を複数指定することができません。  

\kを . にして頂けないでしょうか?  
そのほうがiskeywordの値関係無しにコンマやスペース、アンダースコアなどが使えるので便利だと思います。

**Comment by cohama** [comment]
報告ありがとうございます。
`.`にするのはさすがに大雑把すぎるのでキーワードとカンマくらいにしようかと思います。

なお、現在このリポジトリはほとんどメンテしていません。
`lexima.vim`というプラグインを作って、そちらにも全く同等の機能があるからです。

**Comment by uplus** [comment]
なるほどlexima.vimというものがあったんですね。  
そちらへの移行も考えてみます。  

対応ありがとうございました。
